### ISSUE TITLE
Add `-v/--invert-match` to return non matching entries

### ISSUE THREAD

**Issue by tbm** [zacchiro/beangrep#12]
It would be nice if there was a way to *remove* transactions that match a specific pattern, e.g. show me all transactions from this payee but not if it has this tag.

I'm not sure what the syntax would be, but maybe the pattern could start with a `-`.

**Comment by zacchiro** [comment]
`grep` has `-v/--invert-match` for this.
We can add this to `bean-grep` as well.

**Comment by tbm** [comment]
I'm not sure if that would work.  Because I want to say: search for this, but exclude this. So some should match, some should be invert match.

**Comment by tbm** [comment]
... although I guess one option would be to use a pipe and have two calls.

**Comment by zacchiro** [comment]
> I'm not sure if that would work. Because I want to say: search for this, but exclude this. So some should match, some should be invert match.

I really don't want to go there, because it opens the door to fully boolean AND/OR/NOT queries, which is too complex for a decent UI.

So if you're fine with implementing `-v`, we can make this issue about that.
If not it will be wontfix (for now at least).

**Comment by tbm** [comment]
`-v` with a pipe should work, right?

```
bean-grep foo | bean-grep -v "#foo"
```

**Comment by zacchiro** [comment]
On Thu, May 16, 2024 at 01:00:04AM -0700, Martin Michlmayr wrote:
> `-v` with a pipe should work, right?
> 
> ```
> bean-grep foo | bean-grep -v "#foo"
> ```

You need an explicit "-" as filename, but yes, it should work.

**Comment by zacchiro** [comment]
Caveat to watch out for in implementing this: the default criteria that selects transactions. It should probably *not* be the default when `-v` is given. (Needs some more thoughts in terms of UX…)

**Comment by zacchiro** [comment]
Note also that `-v` is currently use for `--verbose`, so we will need to decide who gets to keep the short flag.
(Probably `--invert-match`, as that is grep behavior and is a quite popular CLI mnemonic for many of us.)

**Comment by zacchiro** [comment]
@tbm so `-v/--invert-match` is implemented in the branch `feature/invert-match`, if you want to give it a try.

*But* it currently doesn't work as (you) expected with the following:
```console
$ bean-grep @Bar tests/data/example.beancount | bean-grep '#chicago' -
```
because the filtered out output of the first invocation cannot be loaded without errors in the second invocation (e.g., there are no `open` directives for accounts there).

This goes in the direction of what you suggested in #5, i.e., be more lenient when loading (but I would still like to file if, say, requested file does not exist).

If the explicit `if ledger[1]:` block in `cli.py` is commented out, the above double/piped invocation works like a charm.
