### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by tbm** [zacchiro/beangrep#7]
You claim to be a Debian person but you ship a tool without man page?  Isn't that one of the biggest sins?

:)

**Comment by zacchiro** [comment]
Possibly, yeah :-)

But I'm not going to work on this myself for now, help/patches welcome.
(Of course the man page should be auto generated from the existing documentation.)

**Comment by zacchiro** [comment]
FWIW, [help2man](https://www.gnu.org/software/help2man/) would be my preferred way of generating the manpage, but it doesn't work out of the box on `bean-grep`, because `--version` is currently missing.
I've filed #15 to track its addition.

**Comment by zacchiro** [comment]
`--version` is now available, making `help2man` work on `bean-grep`

**Comment by zacchiro** [comment]
I fear there is no way to ship a man page with a python package, in a way that make `man bean-grep` works out of the box after `pip install beangrep`. I'd love to be corrected on this if I'm wrong.

If, on the other hand, my impression is confirmed, I'm not exactly sure what the added value of a man page would be over `--help`, if the user needs to know where the manpage is installed (probably something complicated like `~/.cache/virtualenvs/beangrep/lib/python3.11/site-packages/....`) in order to run `man -l` on it.

**Comment by zacchiro** [comment]
The manpage is now automatically generated and shipped with the Python package. I don't think anyone will ever be able to find it, but it's there :-)
